In [1]:
# import all libraries

from pathlib import Path

from modules.random_csv_stock import stock_tickers_random
from modules.alpaca_calls import retrieve_alpaca_dataframes
from modules.calculate_returns import returns_calc

Alpaca Key type: <class 'str'>
Alpaca Secret Key type: <class 'str'>

In [2]:
# function to return MAANG ticker symbols

def stock_tickers_maang():
    maang_tickers = ["META", "AAPL", "AMZN", "NFLX", "GOOGL"]    
    return maang_tickers

maang_stocks = stock_tickers_maang()

### Use the stock_tickers_random function in the modules folder to retrieve 5 random stocks from the CSV file

In [3]:
random_csv_stock = stock_tickers_random()
print(random_csv_stock)

['MCD', 'KO', 'ABT', 'TSLA', 'CSCO']

In [4]:
rand_stock_data = retrieve_alpaca_dataframes(random_cvs_stock)
print(rand_stock_data)

               MCD                                                  \
              open      high      low   close   volume trade_count
2016-09-01  115.51  115.8147  114.860  115.40  3966619       32426
2016-09-02  115.90  116.1100  115.695  115.83  3410123       27140
2016-09-06  117.35  119.2400  116.910  117.25  6337938       48142
2016-09-07  117.27  117.4900  116.440  116.92  2661284       22555
2016-09-08  116.77  117.1100  116.040  116.17  3086302       27255
...            ...       ...      ...     ...      ...         ...
2022-08-25  261.99  262.6800  260.200  262.56  1327763       34567
2022-08-26  262.80  263.2000  256.390  256.95  2347051       43902
2022-08-29  255.50  256.7100  254.590  255.66  2012250       48418
2022-08-30  256.00  256.7200  252.570  253.49  2039729       48102
2022-08-31  254.17  255.6800  252.200  252.28  3102398       55468

                           KO                   ...      TSLA              \
                  vwap   open    high      low  ...    volume trade_count
2016-09-01  115.264858  43.21  43.410  43.2000  ...   7943138       74530
2016-09-02  115.880363  43.56  43.830  43.4700  ...   5977300       58990
2016-09-06  117.663456  43.75  43.800  43.3950  ...   4390572       39194
2016-09-07  116.839264  43.72  43.800  43.5300  ...   3640923       31511
2016-09-08  116.432278  43.65  43.730  43.4500  ...   3377946       31464
...                ...    ...     ...      ...  ...       ...         ...
2022-08-25  261.845665  64.36  64.705  63.9000  ...  53254602     1041465
2022-08-26  258.272220  64.73  64.800  62.9800  ...  57216420      984030
2022-08-29  255.696326  62.71  63.025  62.4100  ...  41881560      693163
2022-08-30  253.952286  62.79  62.910  61.9937  ...  50539842      827061
2022-08-31  253.265325  62.25  62.530  61.7000  ...  52119181      756656

                         CSCO                                                 \
                  vwap   open     high      low  close    volume trade_count
2016-09-01  203.350692  31.42  31.6400  31.2600  31.58  15980457       70639
2016-09-02  198.983866  31.65  31.9500  31.6500  31.83  18156539       70534
2016-09-06  201.739462  31.90  31.9400  31.7000  31.87  17656515       59410
2016-09-07  202.487827  31.79  31.9336  31.7500  31.79  14050458       60646
2016-09-08  197.993461  31.72  31.7500  31.4150  31.47  19913699       77624
...                ...    ...      ...      ...    ...       ...         ...
2022-08-25  295.534560  47.22  47.4300  46.8400  47.27  23039278      106638
2022-08-26  292.622233  47.08  47.2700  45.8800  45.89  20669823      120196
2022-08-29  284.405330  45.78  46.0000  45.4900  45.71  13655721       97015
2022-08-30  279.439363  45.70  45.8700  44.9608  45.24  14277970      102430
2022-08-31  276.374945  45.83  45.8300  44.5850  44.72  22937087      112130


                 vwap
2016-09-01  31.511690
2016-09-02  31.822422
2016-09-06  31.823244
2016-09-07  31.818372
2016-09-08  31.536581
...               ...
2022-08-25  47.177670
2022-08-26  46.197388
2022-08-29  45.753320
2022-08-30  45.290996
2022-08-31  44.864960

[1510 rows x 35 columns]

In [5]:
maang_stock_data = retrieve_alpaca_dataframes(maang_stocks)
print(maang_stock_data)

              META                                                  \
              open    high       low   close    volume trade_count
2016-09-01  126.40  126.63  125.6000  126.17  13536125       81023
2016-09-02  126.84  126.86  126.0000  126.51  12118773       68204
2016-09-06  126.74  129.94  126.4700  129.73  26274857      155056
2016-09-07  130.00  131.98  129.9500  131.05  27990796      159904
2016-09-08  130.92  131.08  129.8100  130.27  15676595       96817
...            ...     ...       ...     ...       ...         ...
2022-08-25  165.00  168.88  164.0200  168.78  15600414      178205
2022-08-26  168.28  170.92  161.6726  161.78  24023633      256217
2022-08-29  160.67  163.05  159.0100  159.17  20052661      215221
2022-08-30  160.24  161.66  155.9100  157.16  19566478      242047
2022-08-31  166.83  167.84  162.1400  162.93  40943310      376594

                          AAPL                  ...     NFLX              \
                  vwap    open    high     low  ...   volume trade_count
2016-09-01  126.205747  106.14  106.80  105.62  ...  4148621       29588
2016-09-02  126.464797  107.67  108.00  106.82  ...  4247182       29522
2016-09-06  128.745007  107.82  108.30  107.51  ...  9036092       59961
2016-09-07  130.921138  107.86  108.76  107.07  ...  6468512       44214
2016-09-08  130.247911  107.12  107.27  105.24  ...  5201208       34422
...                ...     ...     ...     ...  ...      ...         ...
2022-08-25  167.141814  168.68  170.14  168.35  ...  3767106       71648
2022-08-26  164.372086  170.49  171.05  163.56  ...  5349848       91760
2022-08-29  160.467587  161.03  162.90  159.82  ...  7109397      112054
2022-08-30  157.726280  162.13  162.56  157.72  ...  5846834       99035
2022-08-31  164.519913  160.23  160.58  157.14  ...  8615748      126819

                         GOOGL                                      \
                  vwap    open    high       low   close    volume
2016-09-01   97.430264  791.98  792.89  786.3300  791.40   1303460
2016-09-02   97.562739  795.27  797.10  793.2600  796.87   1349896
2016-09-06   99.643372  798.39  810.89  795.4300  808.02   1989537
2016-09-07   99.030509  807.93  810.60  803.7200  807.99   1145724
2016-09-08   99.616908  805.22  808.42  801.0101  802.84   1177660
...                ...     ...     ...       ...     ...       ...
2022-08-25  232.062363  114.20  116.72  114.1100  116.65  16956794
2022-08-26  226.987353  114.62  115.12  110.1900  110.34  37245697
2022-08-29  226.269934  109.99  110.95  108.8000  109.42  21203656
2022-08-30  222.153528  110.13  110.50  107.8000  108.94  27654052
2022-08-31  227.669035  110.60  110.85  108.1300  108.22  28624613


           trade_count        vwap
2016-09-01       20351  790.596257
2016-09-02       20942  795.680483
2016-09-06       31970  805.698861
2016-09-07       19884  806.901307
2016-09-08       19797  803.546573
...                ...         ...
2022-08-25      222757  115.678649
2022-08-26      470822  111.936018
2022-08-29      330865  109.810157
2022-08-30      313471  108.880759
2022-08-31      288861  109.065676

[1510 rows x 35 columns]

In [6]:
maang_returns = returns_calc(maang_stock_data, maang_stocks)
maang_returns.head()

              META                                                            \
              open    high     low   close    volume trade_count        vwap
2016-09-01  126.40  126.63  125.60  126.17  13536125       81023  126.205747
2016-09-02  126.84  126.86  126.00  126.51  12118773       68204  126.464797
2016-09-06  126.74  129.94  126.47  129.73  26274857      155056  128.745007
2016-09-07  130.00  131.98  129.95  131.05  27990796      159904  130.921138
2016-09-08  130.92  131.08  129.81  130.27  15676595       96817  130.247911

              AAPL                  ...          META                     \
              open    high     low  ... daily_returns cumulative_returns
2016-09-01  106.14  106.80  105.62  ...           NaN                NaN
2016-09-02  107.67  108.00  106.82  ...      0.002695           1.002695
2016-09-06  107.82  108.30  107.51  ...      0.025453           1.028216
2016-09-07  107.86  108.76  107.07  ...      0.010175           1.038678
2016-09-08  107.12  107.27  105.24  ...     -0.005952           1.032496

                    AAPL                             AMZN                     \
           daily_returns cumulative_returns daily_returns cumulative_returns
2016-09-01           NaN                NaN           NaN                NaN
2016-09-02      0.009369           1.009369      0.002362           1.002362
2016-09-06     -0.000278           1.009088      0.021270           1.023682
2016-09-07      0.006128           1.015272     -0.005565           1.017986
2016-09-08     -0.026209           0.988663     -0.000535           1.017441

                    NFLX                            GOOGL
           daily_returns cumulative_returns daily_returns cumulative_returns
2016-09-01           NaN                NaN           NaN                NaN
2016-09-02      0.000000           1.000000      0.006912           1.006912
2016-09-06      0.027829           1.027829      0.013992           1.021001
2016-09-07     -0.009392           1.018176     -0.000037           1.020963
2016-09-08      0.005144           1.023413     -0.006374           1.014455

[5 rows x 45 columns]